version: "3.9"
services:
  vaultwarden:
    image: vaultwarden/server:1.30.5
    restart: unless-stopped
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - ROLE=${ROLE:-PRIMARY}
    volumes:
      - vaultwarden-data:/data
    command: >
      /bin/sh -c 'if [ "$ROLE" = "PRIMARY" ]; then /usr/bin/dumb-init /start.sh; else tail -f /dev/null; fi'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  vaultwarden-data:
